# Changes here will be overwritten by Copier
_commit: 5.0.0a5
_src_path: https://github.com/DiamondLightSource/python-copier-template.git
author_email: lee.hudson@diamond.ac.uk
author_name: Lee Hudson
component_lifecycle: experimental
component_owner: accelerator-controls
component_type: library
description: Tool to create a live backup of a dls plc based motion controller
distribution_name: motorplc-backup
docker: false
docs_type: README
git_platform: github.com
github_org: DiamondLightSource
package_name: motorplc_backup
pypi: true
repo_name: motorplc-backup
strict_typing: true
type_checker: pyright
